### ISSUE TITLE
Modules aren't foldable using tree sitter, even with correct indentation

### ISSUE THREAD

**Issue by calebmeyer** [tree-sitter/tree-sitter-ruby#100]
## Screenshot
![image](https://user-images.githubusercontent.com/3342777/50602105-fa066480-0e7b-11e9-969c-a7bb5b4c1c80.png)

## Steps to reproduce
Create a new ruby file and put the following text in it
```ruby
module A
  module B
    class C
      def D
        puts 'test'
      end
    end
  end
end
```
Try to fold using either the fold handles or the `fold-at-indent-level-*` functions.

## Expected Result
You can fold ruby code at modules the same as at classes and methods

## Actual Result
Modules don't fold (at all)

**Comment by Ben3eeE** [comment]
Thanks for contributing 🙇 

This is actually a problem with `atom/language-ruby` and not tree-sitter itself. If you look in https://github.com/atom/language-ruby/blob/ea3824d2539fe982e69d0599c5fadd082879f1c6/grammars/tree-sitter-ruby.cson#L28 you can see that there is no folding rule for `module`.

Using the command `editor:log-cursor-syntax-tree-scope` you can verify that `tree-sitter` parses modules.

A rule like this should make folding modules possible. I don't know the exact rule needed because I don't know ruby well.

```ruby
  {
    type: 'module',
    end: {index: -1}
  }
```

**Comment by calebmeyer** [comment]
Is there a good reference for that CSON file you mentioned? I'm not 100% sure how to read it, or how to test changes if I were to make and PR some.

**Comment by maxbrunsfeld** [comment]
Thanks for the report @calebmeyer! Here's the current docs: https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/#code-folding.
