### ISSUE TITLE
Symbol arrays aren't highlighted correctly

### ISSUE THREAD

**Issue by yorickpeterse** [tree-sitter/tree-sitter-ruby#186]
Ruby allows for symbol arrays, similar to string arrays:

```ruby
%i[foo bar]
```

Unlike string arrays, the highlights aren't correct. For strings, the array contents are highlighted as `TSString`, but for symbols they are highlighted as `TSConstant`:

![Screenshot from 2021-08-06 18-56-54](https://user-images.githubusercontent.com/86065/128545688-eb008ce8-6ab1-473e-839d-add7e34806b2.png)

**Comment by YorickPeterse** [comment]
Related, but it's not the cause:

```
[
  "("
  ")"
  "["
  "]"
  "{"
  "}"
  "%w("
  "%i("
] @punctuation.bracket
```

should probably be also support `%i{`, `%i[`, and their uppercase equivalents (e.g. `%I[`).

**Comment by YorickPeterse** [comment]
Parse tree:

```
symbol_array [0, 0] - [0, 11]
  bare_symbol [0, 3] - [0, 6]
    string_content [0, 3] - [0, 6]
  bare_symbol [0, 7] - [0, 10]
    string_content [0, 7] - [0, 10]
```

Oddly enough `bare_symbol` does exist in `highlights.scm`, but for some reason the correct highlight group isn't applied.

**Comment by serhii-budnik** [comment]
@yorickpeterse I also faced that problem. This might happen because `bare symbol` is located in `@constant` group

https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/ruby/highlights.scm#L153

I tried to add code like that and I got it working
```
vim.api.nvim_set_hl(0, '@constant.ruby', { fg = '#ffc0cb', bg = 'NONE' })
```

not sure if that's a bug or a feature I'm not quite well know how that project works in general but maybe I may spend some time investigating this
