### ISSUE TITLE
Parse heredoc strings & subshells

### ISSUE THREAD

**Issue by robrix** [tree-sitter/tree-sitter-ruby#7]
#4 implemented all of the other literals, but not heredoc strings/subshells, because:
1. There’s no way for us to use a matched token as the end delimiter. We would need something essentially like monadic bind to make this work.
2. Heredoc elements apply to the next line. I don’t know a way to make that work correctly w.r.t. the remainder of the current line:
   
   ``` ruby
   print (<<END + ", world")
   hello
   END
   ```

**Comment by maxbrunsfeld** [comment]
When https://github.com/tree-sitter/tree-sitter-ruby/pull/30 lands, this code will parse as follows:

```
(program [0, 0] - [3, 0]
  (method_call [0, 0] - [0, 25]
    (identifier [0, 0] - [0, 5])
    (argument_list [0, 6] - [0, 25]
      (binary [0, 7] - [0, 24]
        (heredoc_beginning [0, 7] - [0, 12])
        (string [0, 15] - [0, 24]))))
  (heredoc_end [1, 0] - [2, 3]))
```

Because of its textually-disconnected nature, the heredoc is modeled as two separate nodes: a `heredoc_beginning` that includes the `<<END`, and a `heredoc_end`, which includes the rest of the heredoc, and is a *sibling* of the call expression.
